trigger:


pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  dispalyName: Fetch Users from Veracode Platform
  inputs:
    targetType: 'inline'
    script: |
      node index.js --type users --actions fetch --file users.csv --apiID $(apiID) --apiKey $(apiKey)

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/users.csv'
    ArtifactName: 'VeracodeUsers'